# Generated by Django 2.1.1 on 2018-10-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181016_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='interests',
            field=models.ManyToManyField(help_text='관심분야를 선택해 주세요.', related_name='interested_clients', to='accounts.Category'),
        ),
    ]
