# Generated by Django 2.1.1 on 2018-10-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181016_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='profile',
        ),
    ]
