# Generated by Django 2.1.1 on 2018-11-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_artist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(allow_unicode=True, max_length=100),
        ),
    ]
