# Generated by Django 2.1.1 on 2018-10-19 17:21

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
