# Generated by Django 2.1.1 on 2018-10-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_artist_profile'),
        ('artist', '0002_auto_20181020_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Category'),
            preserve_default=False,
        ),
    ]
