# Generated by Django 2.1.1 on 2018-10-20 06:56

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_artist_profile'),
        ('artist', '0003_auto_20181020_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ManyToManyField(to='accounts.Category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=200, validators=[artist.models.min_length_3_validator]),
        ),
    ]
