# Generated by Django 2.1.1 on 2018-10-21 07:31

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20181020_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, upload_to=artist.models.upload_to),
        ),
    ]
