# Generated by Django 2.1.1 on 2018-10-22 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0006_auto_20181021_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
