# Generated by Django 2.1.1 on 2018-10-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_work_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='work',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
