# Generated by Django 2.1.1 on 2018-11-12 08:42

import artist.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20181027_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=artist.models.upload_to)),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Work'),
        ),
    ]
