# Generated by Django 2.1.1 on 2018-11-12 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_auto_20181112_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 12, 10, 48, 21, 548229, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
